### ISSUE TITLE
ERROR 

### ISSUE THREAD

**Issue by AshantyTTV** [KYGAS/ValkRuneburst#2]
Hi, I am getting this error when i stop the toolbox.
[16:34:13.306] Unable to store settings! The full error message is:
[16:34:13.307] Error: EPERM: operation not permitted, open 'C:\Users\Ashanty\AppData\Local\Programs\TeraToolbox\mods\ValkRuneburst\config.json'
    at Object.openSync (fs.js:440:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.writeFileSync (fs.js:1265:35)
    at Mod.saveSettings (C:\Users\Ashanty\AppData\Local\Programs\TeraToolbox\bin\mod.js:717:20)
    at Mod.unload (C:\Users\Ashanty\AppData\Local\Programs\TeraToolbox\bin\mod.js:405:18)
    at Mod.destructor (C:\Users\Ashanty\AppData\Local\Programs\TeraToolbox\bin\mod.js:393:14)
    at ModManager.unload (C:\Users\Ashanty\AppData\Local\Programs\TeraToolbox\bin\mod-manager.js:151:13)
    at C:\Users\Ashanty\AppData\Local\Programs\TeraToolbox\bin\mod-manager.js:110:22
    at Map.forEach (<anonymous>)
    at ModManager.unloadAll (C:\Users\Ashanty\AppData\Local\Programs\TeraToolbox\bin\mod-manager.js:108:25) {
  errno: -4048,
  syscall: 'open',
  code: 'EPERM',
  path: 'C:\\Users\\Ashanty\\AppData\\Local\\Programs\\TeraToolbox\\mods\\ValkRuneburst\\config.json'
}

**Comment by KYGAS** [comment]
It's not module related, you don't have permissions to make changes to files...
I would guess you aren't using admin version?
And if you are you should move proxy to a less "controlled" area.
Put it on your Desktop or in your C:\ disk, not in AppData...

**Comment by Nullaris-Dev** [comment]
Oh i understand. Thanks.
